version: '3.8'

services:
  crm-natale:
    build: .
    container_name: crm-natale
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:///data/crm_natale.db
      - PORT=5000
      - FLASK_DEBUG=False